GD_API_DISPLAY_NAME = 'nsmedia'
# set dataset
MNC_DATASET = 'MNC'
MNC_API = 'NSMGAPI'
ECONOMICS_API = 'EconomicsNSMG'
MNC_API_CREDENTIALS = 'mnc_api_credentials.txt'
ECONOMICS_API_CREDENTIALS = 'economics_api_credentials.txt'
ECONOMICS_API_URL = f'http://apidata.globaldata.com/EconomicsNSMG/api/Content/GetCityEconomicsListing?DisplayName={GD_API_DISPLAY_NAME}&TokenId='
MNC_API_URL = f'http://apidata.globaldata.com/NSMGAPI/api/MNCSegments/GetMNCSegmentsListing?DisplayName={GD_API_DISPLAY_NAME}&TokenId='
